# Generated by Django 2.2 on 2021-04-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('F', 'формируется'), ('S', 'отправлен'), ('P', 'оплачен'), ('D', 'отменен')], db_index=True, default='F', max_length=1, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='время'),
        ),
    ]
