# Generated by Django 2.2 on 2021-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_auto_20210423_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='add_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='время'),
        ),
    ]
